export const greetings = {
  morning: [
    "Good morning, {name}! Let’s make today a profitable one.",
    "Top of the morning, {name}! Time to set the tone for success.",
    "Morning hustle, {name}! Great things don’t wait.",
    "New day, new deals, {name}. Let’s move numbers today.",
    "The early bird earns the market share. Let’s go, {name}!",
    "Coffee brewed, mind sharp — execute, {name}!",
    "Morning momentum is the CEO of success. Own it, {name}.",
    "Sun’s up, spreadsheets open — let’s dominate, {name}!",
    "Wake. Plan. Close. Repeat. It’s your formula, {name}.",
    "Morning, {name}! Let’s turn ideas into income.",
  ],
  afternoon: [
    "Good afternoon, {name}! Keep the workflow strong.",
    "Momentum check, {name} — numbers don’t nap.",
    "Midday magic happens in execution, {name}.",
    "It’s a good hour to push one more sale, {name}.",
    "The best businesses sprint after lunch — keep going, {name}.",
    "Keep your focus sharp and your vision sharper, {name}.",
    "Still time to outpace the competition, {name}.",
    "Meetings done, targets next. Let’s finish strong, {name}.",
    "No coasting allowed, {name}. Afternoon grind mode: ON.",
    "Success favors the focused, {name}. Stay in the zone.",
  ],
  evening: [
    "Good evening, {name}. Let’s review, reflect, and refuel.",
    "Wrap it up strong, {name} — the market never sleeps.",
    "Evenings build tomorrow’s strategy. Stay sharp, {name}.",
    "Profits made, lessons learned. You’re evolving, {name}.",
    "Evening glow pairs well with business growth, {name}.",
    "Let’s close the day with clarity and class, {name}.",
    "You’ve earned the pause, {name} — recharge and rise again.",
    "Every sunset reminds us: consistency compounds, {name}.",
    "Wind down but don’t tune out. Tomorrow’s plan awaits, {name}.",
    "The day’s report: productive, progressive, promising. Well done, {name}.",
  ],
};
